# Generated by Django 5.2 on 2025-04-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='session_name',
        ),
    ]
