# Generated by Django 5.2 on 2025-04-20 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_customuser_session_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['-created_at'], 'verbose_name': 'Группа чатов', 'verbose_name_plural': 'Группы чатов'},
        ),
        migrations.AddField(
            model_name='groups',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='chats',
            field=models.JSONField(default=list, help_text='Список URL чатов в формате JSON', verbose_name='Ссылки на чаты'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
