# Generated by Django 5.2 on 2025-04-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_groups_options_groups_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={},
        ),
        migrations.RemoveField(
            model_name='groups',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='groups',
            name='chats',
            field=models.JSONField(default=list, verbose_name='Ссылки на чаты'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
