# Generated by Django 5.2 on 2025-04-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_groups_chats_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='additional_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='is_step1_completed',
            field=models.BooleanField(default=False),
        ),
    ]
