# Generated by Django 5.2 on 2025-04-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_session_additional_field_session_is_step1_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_name',
            new_name='session',
        ),
    ]
