# Generated by Django 5.2 on 2025-04-21 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_rename_session_name_session_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_us', to=settings.AUTH_USER_MODEL),
        ),
    ]
